apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: webapp-postgres
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: webapp-postgres
  template:
    metadata:
      labels:
        app: webapp-postgres
    spec:
      containers:
        - name: {{ .Values.dbContainer.name }}
          image: {{ .Values.dbContainer.image }}
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: db-values-cfgmp
                  key: dbName
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: db-values-cfgmp
                  key: dbUser
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: dbPassword
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-pvc
              mountPath: /mnt/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.pvc.storage }}
        storageClassName: {{ include "webapp-storage.fullname" . }}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: webapp-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  clusterIP: None
