{{- range $name := keys .Values.imagePullSecrets }}
apiVersion: v1
data:
  .dockerconfigjson: {{ get $.Values.imagePullSecrets $name }}
kind: Secret
metadata:
  name: {{ $name | quote }}
  labels:
    {{- include "webapp-cve.labels" $ | nindent 4 }}
type: kubernetes.io/dockerconfigjson
{{- end }}