---
{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    {{- include "webapp-cve.labels" . | nindent 4 }}
  name: {{ include "webapp-cve.roleName" . }}
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
{{- if .Values.rbac.extraRules }}
{{- toYaml .Values.rbac.extraRules | nindent 2 }}
{{- end }}
{{- end }}