---
{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "webapp-cve.labels" . | nindent 4 }}
  name: {{ include "webapp-cve.fullname" . }}-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "webapp-cve.roleName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "webapp-cve.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}