apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  dbPassword: {{ .Values.dbCredentials.dbPassword | b64enc | quote }}
  {{ if and .Values.storageClass.kmsKeyId (gt (len .Values.storageClass.kmsKeyId) 0)}}
  kmsKeyId: {{ .Values.storageClass.kmsKeyId | b64enc | quote }}
  {{ end }}
