apiVersion: batch/v1
kind: Job
metadata:
  name: webapp-cve-job
  labels:
    app: webapp-cve
spec:
  template:
    metadata:
      labels:
        app: webapp-cve
    spec:
      imagePullSecrets:
        {{- include "webapp-cve.imagePullSecrets" . | nindent 8 }}
      containers:
        - name: {{ .Values.appContainer.name }}
          image: {{ .Values.appContainer.image }}
          env:
            - name: KAFKA_BROKER
              valueFrom:
                configMapKeyRef:
                  name: kafka-producer-config
                  key: kafkaHost
            - name: KAFKA_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: kafka-producer-config
                  key: topic
            - name: KAFKA_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: kafka-producer-config
                  key: username
            - name: KAFKA_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: kafka-producer-config
                  key: password
            - name: SASL_MECHANISM
              valueFrom:
                configMapKeyRef:
                  name: kafka-producer-config
                  key: mechanism
            - name: BATCH_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  name: kafka-producer-config
                  key: batchTimeout
            - name: MAX_BATCH_SIZE
              valueFrom:
                configMapKeyRef:
                  name: kafka-producer-config
                  key: maxBatchSize
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

      restartPolicy: {{ default "Never" .Values.restartPolicy }}
