apiVersion: v1
kind: Pod
metadata:
  name: {{ include "webapp-cve.fullname" . }}
  labels:
    {{- include "webapp-cve.labels" . | nindent 4 }}
spec:
  imagePullSecrets:
    {{- include "webapp-cve.imagePullSecrets" . | nindent 4 }}
  initContainers:
  - name: {{ .Values.initContainer.name }}
    image: {{ .Values.initContainer.image }}
    env:
    - name: FLYWAY_URL
      valueFrom:
        configMapKeyRef:
          name: db-values-cfgmp
          key: dbUrl
    - name: FLYWAY_USER
      valueFrom:
        configMapKeyRef:
          name: db-values-cfgmp
          key: dbUser
    - name: FLYWAY_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-credentials
          key: dbPassword
    - name: FLYWAY_SCHEMAS
      valueFrom:
        configMapKeyRef:
          name: db-values-cfgmp
          key: flywaySchemas
    - name: FLYWAY_DEFAULT_SCHEMA
      valueFrom:
        configMapKeyRef:
          name: db-values-cfgmp
          key: flywayDefaultSchema
    - name: FLYWAY_LOCATIONS
      valueFrom:
        configMapKeyRef:
          name: db-values-cfgmp
          key: flywayLocations
  containers:
  - name: {{ .Values.appContainer.name }}
    image: {{ .Values.appContainer.image }}
    env:
      - name: DB_HOST
        valueFrom:
          configMapKeyRef:
            name: db-values-cfgmp
            key: dbHost
      - name: DB_USER
        valueFrom:
          configMapKeyRef:
            name: db-values-cfgmp
            key: dbUser
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: db-credentials
            key: dbPassword
      - name: DB_NAME
        valueFrom:
          configMapKeyRef:
            name: db-values-cfgmp
            key: dbName
      - name: DB_PORT
        valueFrom:
          configMapKeyRef:
            name: db-values-cfgmp
            key: dbPort
      - name: BATCH_SIZE
        valueFrom:
          configMapKeyRef:
            name: db-values-cfgmp
            key: batchSize
  restartPolicy: {{ default "Never" .Values.restartPolicy }}